name: Trigger auto deployment for moneykey-api

on:
  push:
    branches: 
      - master # Ändra till main om din branch heter det
    paths:
      - '**'

  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write 
      contents: read 

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MONEYKEYAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MONEYKEYAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MONEYKEYAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./Dockerfile 
          containerAppName: moneykey-api
          resourceGroup: moneykey-group
          # Här kopplar vi ihop allt med ditt nya register
          imageToBuild: ${{ secrets.MONEYKEYAPI_REGISTRY_SERVER }}/moneykey-api:${{ github.sha }}
          registryUrl: ${{ secrets.MONEYKEYAPI_REGISTRY_SERVER }}
          registryUsername: ${{ secrets.MONEYKEYAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MONEYKEYAPI_REGISTRY_PASSWORD }}
